// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bxjderygqhdpizkkumtq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ4amRlcnlncWhkcGl6a2t1bXRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0NjA1MzIsImV4cCI6MjA2OTAzNjUzMn0.8xlCxjQ5jzv8LwPfEl41OZUFyfGANjcfQ4nEkCr2BVo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});